[package]
name = "prae"
version = "0.4.2"
authors = ["Alex Ryapolov <ryapolov@pm.me>"]
edition = "2018"
license = "Unlicense"
description = "Define types that promise to be always valid"
documentation = "https://docs.rs/prae"
readme = "../README.md"
repository = "https://github.com/teenjuna/prae"
keywords = ["validation", "macro", "invariant", "generation"]
categories = ["development-tools"]

[dependencies]
prae_macro = { version = "0.2.1", path = "../prae_macro" }
serde = { version = "1.0.126", optional = true }
thiserror = "1.0.25"

[dev-dependencies]
serde_json = "1.0.64"
serde = { version = "1.0.126", features = ["derive"] }
