[package]
name = "prae"
version = "0.3.1"
authors = ["Alex Ryapolov <ryapolov@pm.me>"]
edition = "2018"
license = "Unlicense"
description = "Define types that promise to be always valid"
documentation = "https://docs.rs/prae"
readme = "../README.md"
repository = "https://github.com/teenjuna/prae"
keywords = ["validation", "macro", "invariant", "generation"]
categories = ["development-tools"]

[dependencies]
prae_macro = { version = "0.2.0", path = "../prae_macro" }
thiserror = "1.0.25"
